name: "PyTest PR"

on:
  # Use pull_request, not pull_request_target because we run arbitrary code in
  # this workflow. c.f.
  # https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest dependencies
        run: pip install pytest pytest-md pytest-emoji
      - name: developer mode install
        run: pip install -e .
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: true
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mypy dependencies
        run: pip install mypy
      - name: Runs mypy
        run: mypy src/blueair_api --explicit-package-bases

